### ISSUE TITLE
Error: Array index is out of range.

### ISSUE THREAD

**Issue by Scoup** [algernon-A/Realistic-Population-Revisited#35] opened 2022-06-02 15:56 UTC
I'm having an error with 2 assets of green cities. I'm trying a workaround (removing the building or supress). I removed all mods and let only this one and still happening. Enabling all other mods and removing only this one the problem disapear.

eco_residential_high01_2x3level4:

```
An exception occured during BuildingAI simulation step.
Asset: eco_residential_high01_2x3level4
BuildingID: 40034
Type: ResidentialBuildingAI
Severity: High

System.IndexOutOfRangeException: Array index is out of range.
at EconomyManager.GetTaxRate (ItemClass/Service,ItemClass/SubService,ItemClass/Level,DistrictPolicies/Taxation) <0x00063>
at EconomyManager.AddResource (EconomyManager/Resource,int,ItemClass/Service,ItemClass/SubService,ItemClass/Level,DistrictPolicies/Taxation) <0x0006e>
at ResidentialBuildingAI.SimulationStepActive (uint16,Building+,Building/Frame+) <0x008df>
at CommonBuildingAI.SimulationStep (uint16,Building+,Building/Frame+) <0x00c3a>
at (wrapper dynamic-method) PrivateBuildingAI.PrivateBuildingAI.SimulationStep_Patch0 (PrivateBuildingAI,uint16,Building+,Building/Frame+) <0x0005d>
at (wrapper dynamic-method) ResidentialBuildingAI.ResidentialBuildingAI.SimulationStep_Patch0 (ResidentialBuildingAI,uint16,Building+,Building/Frame+) <0x00043>
at BuildingAI.SimulationStep (uint16,Building+) <0x00058>
at (wrapper dynamic-method) CommonBuildingAI.CommonBuildingAI.SimulationStep_Patch1 (CommonBuildingAI,uint16,Building+) <0x0006f>
at HealkitMod.Patches.BuildingManagerPatch.SimulationStep (BuildingAI,uint16,Building+) <0x00049>

```

eco_residential_high01_3x2level4:

```
An exception occured during BuildingAI simulation step.
Asset: eco_residential_high01_3x2level4
BuildingID: 5475
Type: ResidentialBuildingAI
Severity: High

System.IndexOutOfRangeException: Array index is out of range.
at EconomyManager.GetTaxRate (ItemClass/Service,ItemClass/SubService,ItemClass/Level,DistrictPolicies/Taxation) <0x00063>
at EconomyManager.AddResource (EconomyManager/Resource,int,ItemClass/Service,ItemClass/SubService,ItemClass/Level,DistrictPolicies/Taxation) <0x0006e>
at ResidentialBuildingAI.SimulationStepActive (uint16,Building+,Building/Frame+) <0x008df>
at CommonBuildingAI.SimulationStep (uint16,Building+,Building/Frame+) <0x00c3a>
at (wrapper dynamic-method) PrivateBuildingAI.PrivateBuildingAI.SimulationStep_Patch0 (PrivateBuildingAI,uint16,Building+,Building/Frame+) <0x0005d>
at (wrapper dynamic-method) ResidentialBuildingAI.ResidentialBuildingAI.SimulationStep_Patch0 (ResidentialBuildingAI,uint16,Building+,Building/Frame+) <0x00043>
at BuildingAI.SimulationStep (uint16,Building+) <0x00058>
at (wrapper dynamic-method) CommonBuildingAI.CommonBuildingAI.SimulationStep_Patch1 (CommonBuildingAI,uint16,Building+) <0x0006f>
at HealkitMod.Patches.BuildingManagerPatch.SimulationStep (BuildingAI,uint16,Building+) <0x00049>
```

**Comment by algernon-A** [comment] 2022-06-02 23:28
Those messages are referencing multiple Harmony patches that aren't applied by this mod - in fact, not one single method in that stacktrace is used by this mod (plus you're using the Extended Error Reporting mod, which you really shouldn't be if you're troubleshooting mod issues - it causes far too many issues of its own).

Most likely you are using a mod that's incompatible with this one, and that's breaking when you enable this mod.  Please post your full output log so I can see which mod is causing the issue.

**Comment by Scoup** [comment] 2022-06-03 01:55
I didn't know the issue with Extended Error Reporting, disabled it to get the logs. I let enabled only:
- [Realistic Population 2 2.0.2](https://steamcommunity.com/sharedfiles/filedetails/?id=2025147082)
- [Instant Return To Desktop](https://steamcommunity.com/sharedfiles/filedetails/?id=2037888659)
- [Loading Screen Mod temporary fix for Airports DLC](https://steamcommunity.com/sharedfiles/filedetails/?id=2731207699)
- [Harmony 2.2-0 (Mod Dependency)](https://steamcommunity.com/workshop/filedetails/?id=2040656402)

I could still reproduce the error. Logs: [Player.log](https://github.com/algernon-A/Realistic-Population-Revisited/files/8828941/Player.log).

I actually found all the builds with problems (destroying them fixed the problem, but if the same assets came back the problem returns).

**Comment by algernon-A** [comment] 2022-06-03 02:21
Thanks for the logs and the modlist.  Which specific buildings are they?

**Comment by Scoup** [comment] 2022-06-03 03:03
`eco_residential_high01_2x3level4`and `eco_residential_high01_3x2level4`

**Comment by algernon-A** [comment] 2022-06-03 13:22
I'm not able to reproduce.  Are you able to reproduce the issue on a new (test) city?

**Comment by Scoup** [comment] 2022-06-03 13:37
I tried a new empty map and I could not reproduce the issue. Now I have no idea what is going on in my city.

**Comment by algernon-A** [comment] 2022-06-03 15:08
Can you post your save?  Sharing on Steam Workshop and putting the link here is fine.

**Comment by Scoup** [comment] 2022-06-03 15:59
Sure, here is the link: https://steamcommunity.com/sharedfiles/filedetails/?id=2816350414
Thanks for the help. I can try to avoid using these assets in this city if we can't find the problem.

**Comment by algernon-A** [comment] 2022-06-09 02:19
I think the issue is data corruption in your save; I note that some other mods (e.g. Intersection Marking Tool) are also reporting errors, and there are multiple warning icons on buildings on load that aren't justified by the city state.

I've been unable to reproduce on any other save or new game; I'll close this for now, as I don't think there's anything further that can be done.  Please let me know if the issue reoccurs on any other save.

**Closed as completed by algernon-A** 2022-06-09 02:19 UTC
